server:
  port: 0 # random open port


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    default-models-expand-depth: -1
    display-request-duration: true
    enabled: true
    operations-sorter: alpha
    path: /swagger-ui