name: Continuous Delivery

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

concurrency:
  group: continuous-delivery

jobs:
  build-and-run-tests-and-deploy:
    name: Build, Run Tests, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Set up JDK 24
        uses: actions/setup-java@v5
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
      - name: Run Maven
        run: make mvn-deploy-cd
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}